### PR TITLE
More changes and fixes

### PR DESCRIPTION
**Pull request by jackkjhsu**
Hi Thomas,

Please let me know if these changes are ok. Also, the new refactoring broke the context menu in that the checkboxes do not respond to clicks any more. Could you have a look at that as well?

Also, during the course of these changes, I've noticed that all the custom events are created and dispatch on a per element basis. Perhaps when I get a chance, I'll look into redoing the custom events with event delegation technique to make things more robust and efficient.

Thanks again.

### CODE REVIEW

**Comment by lekoala** [comment]
@jackkjhsu hey thanks. it's still working in progress but i believe the new refactor brings a much cleaner approach for many things

**Comment by lekoala** [comment]
@jackkjhsu the context menu seem to work fine for me so i'm not sure what's going on. i'm not sure what is the issue also for the custom element being created on a per element basis. i'm dispatching everything from the grid (at least it should :) ) using the new dispatch helper function that makes the syntax much easier to work with.

**Comment by jackkjhsu** [comment]
> @jackkjhsu hey thanks. it's still working in progress but i believe the new refactor brings a much cleaner approach for many things

Found where the issue lies, the visibleColumns() method. It was filtering by `col.hidden === false`, which was too strict, not allowing unset hidden property. I've now changed the predicate to `!col.hidden` . This should now work for set or unset column.hidden properties. I will be making another pull request shorly.

Thanks

**Comment by jackkjhsu** [comment]
> @jackkjhsu the context menu seem to work fine for me so i'm not sure what's going on. i'm not sure what is the issue also for the custom element being created on a per element basis. i'm dispatching everything from the grid (at least it should :) ) using the new dispatch helper function that makes the syntax much easier to work with.

There's no issue with the custom event creation and dispatching now. I am just proposing that we can look into using event delegation technique to optimize things. As for the context menu, a fix is coming for cases where column.hidden property is not set, making its default false.

Thanks

**Pull request merged**
