### PR TITLE
Minor changes to improve API usability and error handling.

### PR DESCRIPTION
**Pull request by jackkjhsu**
Hi Thomas,

Another round of minor changes for some improvements. Please let me known if these are ok.

cc'ing @fiztech-code for awareness.

Thanks!

### CODE REVIEW

**Comment by lekoala** [comment]
i'm not sure about the $() getters
they are not scoped
also, i don't see much benefits in make the query each time, storing in this.table = this.querySelector('table') makes the selection once and for all, otherwise call this.table as a getter is going to make the query each time. not a big deal (it's quite fast) but still, if it can be avoided.
get table() { return $("table"); } is not doing that does it?

**Comment by jackkjhsu** [comment]
Hi Thomas,
You’re right about the getters, they should be scoped. Also, about this.table, I’ll put it back in the _connected() method as it was before. Will push another commit shortly.
Thanks for catching these.

**Comment by jackkjhsu** [comment]
Hi Thomas,
I just push my latest changes, which not only includes the scoping issue with the getter methods but it also addresses an issue with the aria-rowcount attribute not updating when the reload method is called. I moved the setAttribute call from configureUi method to loadData method, which ensures that the aria-rowcount attribute gets updated whenever data gets loaded to the grid.

Please let me know if you see any other issues.

Thanks again

**Comment by lekoala** [comment]
merged

i've also fixed a pagination issue when using the api

and also improved the zebra styling, it's more in line with whats bootstrap 5 does in 5.3

**Comment by jackkjhsu** [comment]
> merged
> 
> i've also fixed a pagination issue when using the api
> 
> and also improved the zebra styling, it's more in line with whats bootstrap 5 does in 5.3

👍 Thank you very much Thomas!

**Pull request merged**
