### PR TITLE
Changes relating to responsive column headers

### PR DESCRIPTION
**Pull request by jackkjhsu**
Hi Thomas,

In addition to these commits, I'm also wondering the following:

Could we create a dist folder in the root to house the following files?
- data-grid.js (unminified,  but bundled with all plugins, utils, and imports from /data-grid.js)
- data-grid.min.js (moved from /data-grid.min.js - minified and bundled with all plugins and dependencies)
- data-grid.css (copy of /data-grid.css unminified)
- data-grid.min.css (moved from /data-grid.min.css - minified)

Thank you again!

### CODE REVIEW

**Comment by lekoala** [comment]
@jackkjhsu that looks great. yes we can create a dist folder, no worries
one important thing, could you apply your changes to the scss file and then simply compile the scss to css ? it seems you make the changes directly in the compiled css file and that's not very convenient.

**Comment by lekoala** [comment]
@jackkjhsu fyi, it's very likely i'm going to make changes in how the responsive mode is handled. It's very likely i'll use a solution like many other data grids where you have a little toggle icon that appears at the start of a row when some rows are hidden due to lack of space in small screens. this will allow to have a more consistent layout.

**Comment by jackkjhsu** [comment]
> @jackkjhsu that looks great. yes we can create a dist folder, no worries one important thing, could you apply your changes to the scss file and then simply compile the scss to css ? it seems you make the changes directly in the compiled css file and that's not very convenient.

I usually deal with css directly and not bother with scss in my own work, but I will look into applying these css changes in scss and then do a compile into css.

Thanks

**Comment by jackkjhsu** [comment]
> @jackkjhsu fyi, it's very likely i'm going to make changes in how the responsive mode is handled. It's very likely i'll use a solution like many other data grids where you have a little toggle icon that appears at the start of a row when some rows are hidden due to lack of space in small screens. this will allow to have a more consistent layout.

Yeah, that sounds good. Even with the new changes showing the column header THs, I don't think it uses the limited space perfectly.
Thanks

**Review by jackkjhsu — COMMENTED** [review]
Hi Thomas,

Just committed an update to the scss file and css and js rebuild. Please take a look when you get a chance. I hope this is good enough. Thanks

**Comment by lekoala** [comment]
@jackkjhsu mostly good ! i'm going to make a couple of changes but that looks great

**Comment by lekoala** [comment]
@jackkjhsu i made a couple of changes on master you can check if that doesn't break anything for you ?

**Comment by jackkjhsu** [comment]
> @jackkjhsu i made a couple of changes on master you can check if that doesn't break anything for you ?

This business of toggling various areas, including the column headers, of the grid based on the grid's properties, i.e. responsive, sort, filter and selectable, quickly get pretty complex to do it properly with just css. The latest changes introduced an issue where the "Column Filters" label is hidden when it needs to be shown. I think it needs to be shown whenever the grid's width < 768 and [responsive][filter="true"] . So I am creating another pull request where I kind of went back to the changes I made previously but with a few tweaks. The css styles at the bottom of scss file is not really pretty but I think it's necessary to cover all different states of the grid without resorting to javascript hacks.

I am also including a new change to fix an issue where the data displayed in the columns is not aligned after the columns are reordered and the grid retrieves the data in server mode. 

Thanks Thomas

**Comment by lekoala** [comment]
@jackkjhsu yes i'm not happy with the current logic, it should be simpler. Overall, I think a big refactor is needed anyway :-) ideally I'd like to have each feature clearly split in a distinct class.

**Comment by jackkjhsu** [comment]
> @jackkjhsu yes i'm not happy with the current logic, it should be simpler. Overall, I think a big refactor is needed anyway :-) ideally I'd like to have each feature clearly split in a distinct class.

@lekoala, I think it's probably good to do a refactoring after the responsive column header redesign you talked about earlier. Nevertheless, it is functioning for now as it's supposed to, and even the column reordering is working as intended in responsive mode. I will keep the changes coming as needed, since I will be working with the data-grid for the next little while and trying to incorporate it in a working web app. I think that's the best way to weed out any bug it may still have. 

Thanks again Thomas.

**Pull request merged**
