### PR TITLE
Some minor fixes

### PR DESCRIPTION
**Pull request by jackkjhsu**
Hi Thomas,

I just pushed some changes for some minor fixes. Most notably, an issue with the footer width resizing when hiding or showing columns using the context menu. This issue only occurs on Chrome and Edge that seems to have something to do with how the browser renders the flexbox. I tried fixing it with css but couldn't get any of the css fixes I tried to work. Fortunately, the fixPage method works to address the Chrome rendering issue.

I also updated the npm packages and got some css build deprecation warnings from the latest version of sass. So I reverted to v1.77.6 without making more changes to get rid of the warning.
  
Please let me know if the changes are ok.

Thanks Thomas

### CODE REVIEW

**Comment by jackkjhsu** [comment]
Thanks Thomas 👍

**Comment by jackkjhsu** [comment]
Hi Thomas,
A colleague of mine Nik Kojevnikov (@fiztech-code) just completed a plugin for caching various states of data-grid (i.e. page number, sorted column, etc). We have tested this plugin (save-state.js) together, and he'll be making a pull request for it soon. I hope this is ok with you.
Aside from the new plugin, I also have a few changes coming up. But I will do it with another pull request of my own.

Thank you Thomas

**Comment by lekoala** [comment]
sure, he's welcome and i'm happy to review it

**Comment by jackkjhsu** [comment]
Thank you very much Thomas! 👍

**Pull request merged**
