### PR TITLE
Fixed minor css issue that caused column header row to be hidden when column headers are populated.

### PR DESCRIPTION
**Pull request by jackkjhsu**
Hi Thomas,

Sorry to bug you again. I missed a css bug that caused the column header row to be hidden when it's not supposed to.
This should be fixed now.

If it's ok with you, would you mind publish this latest version to npm?

Thank you very much again.

### CODE REVIEW

**Comment by jackkjhsu** [comment]
👍

**Comment by jackkjhsu** [comment]
Hi Thomas, could you also push this latest release to npm? Thank you again.

**Comment by lekoala** [comment]
done

**Comment by jackkjhsu** [comment]
👍 Thank you very much Thomas!

**Pull request merged**
